### ISSUE TITLE
_demo: dragging outside of application window results in crash.

### ISSUE THREAD

**Issue by mewmew** [ebitenui/ebitenui#8]
First off, really cool UI project! The demo looks great!

I was playing around with the various widgets and encountered a crash when dragging outside of the application window. See screenshot below (right before the crash).

Stack trace is attached below (at rev 466226fd04c39712cd2faba3413dde9685b93ee4).

![screenshot_2020-12-31_00:19:38](https://user-images.githubusercontent.com/1414531/103386155-cd829300-4afd-11eb-8453-06a995154568.png)

```
$ _demo
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x673226]

goroutine 8 [running]:
main.(*dragContents).Update(0xc00005cc40, 0x0, 0x0, 0x161, 0x15e, 0x0, 0x0)
	/tmp/ebitenui/_demo/dnd.go:38 +0x26
github.com/blizzy78/ebitenui/widget.(*DragAndDrop).draggingState.func1(0xc00019b080, 0x753690, 0x0, 0x0)
	/tmp/ebitenui/widget/dnd.go:180 +0x3c9
github.com/blizzy78/ebitenui/widget.(*DragAndDrop).Render(0xc000069c70, 0xc00019b080, 0x753690)
	/tmp/ebitenui/widget/dnd.go:113 +0x3e
github.com/blizzy78/ebitenui/widget.renderDeferredRenderQueue(0xc00019b080)
	/tmp/ebitenui/widget/widget.go:359 +0x84
github.com/blizzy78/ebitenui/widget.RenderWithDeferred(0xc00019b080, 0xc0002461b0, 0x3, 0x3)
	/tmp/ebitenui/widget/widget.go:347 +0x109
github.com/blizzy78/ebitenui.(*UI).render(0xc00015dc20, 0xc00019b080)
	/tmp/ebitenui/ui.go:140 +0x2a6
github.com/blizzy78/ebitenui.(*UI).Draw(0xc00015dc20, 0xc00019b080)
	/tmp/ebitenui/ui.go:64 +0x21f
main.(*game).Draw(0xc000010d00, 0xc00019b080)
	/tmp/ebitenui/_demo/main.go:376 +0x38
github.com/hajimehoshi/ebiten/v2.(*imageDumperGameWithDraw).Draw(0xc000a8a420, 0xc00019b080)
	/home/u/goget/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.0.2/run.go:120 +0x48
github.com/hajimehoshi/ebiten/v2.(*uiContext).draw(0xaa0640)
	/home/u/goget/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.0.2/uicontext.go:214 +0x6e
github.com/hajimehoshi/ebiten/v2.(*uiContext).Draw(0xaa0640, 0x0, 0x0)
	/home/u/goget/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.0.2/uicontext.go:174 +0xb1
github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.(*UserInterface).update(0x9271a0, 0x20001, 0x1)
	/home/u/goget/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.0.2/internal/uidriver/glfw/ui.go:871 +0x30d
github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.(*UserInterface).loop(0x9271a0, 0x0, 0x0)
	/home/u/goget/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.0.2/internal/uidriver/glfw/ui.go:914 +0xcf
github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.(*UserInterface).run(0x9271a0, 0x0, 0x0)
	/home/u/goget/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.0.2/internal/uidriver/glfw/ui.go:769 +0x2bd
github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.(*UserInterface).Run.func1(0x9271a0, 0xc000a6cae0)
	/home/u/goget/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.0.2/internal/uidriver/glfw/ui.go:602 +0x72
created by github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.(*UserInterface).Run
	/home/u/goget/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.0.2/internal/uidriver/glfw/ui.go:594 +0x12f
```

**Comment by blizzy78** [comment]
Fixed, thanks!
